### ISSUE TITLE
Remember previous settings/Config file presets

### ISSUE THREAD

**Issue by sanscriptum** [GwenTastic/Twee-File-Splitter#1]
This tool is exactly what I was looking for, thank you so much! But the only issue I have is that it doesn't remember previous settings once you close it, which is quite daunting when you have hundreds of rules. Can you please add that?

**Comment by GwenTastic** [comment]
TL;DR; Done, it's now possible via Profiles!

The ability to have multiple profiles where Rules are saved/stored under Profiles and being able to simply switch to a different set of rules by selecting a different Profile had been on my mind since i first started the project. But it always seemed like a low priority since it's not really clear to me how many people use this tool and i myself don't use it as much.
Only needed it once or twice when switching over from the Twine Application to VS Code + Tweego, but nowadays i usually start outright with VS Code + Tweego.
